### PR TITLE
Initial hw1 for Rahil Makadia (makadia2)

### PR DESCRIPTION
**Pull request by rahil-makadia**

### CODE REVIEW

**Comment by ravadap** [comment]
I don't know how to assign myself, but I will do this code review

**Comment by rahil-makadia** [comment]
I just added you as reviewer lmk if you don't see it

**Comment by ravadap** [comment]
Code Review

- Code and algorithms look good and correctly implemented. Code is also well commented. 
- This may be personal preference, but the code is a little bit hard to read due to the algorithms implemented in one big function. It may increase readability to break some of the code up or create helper functions.
- Potentially could have plotting functions be global for both the pendulum and the gridworld instead of separate functions for each scenario. 
- All of the required files and output plots are present and .py files are correctly named.

Overall the code looks good. I don't see any major sources of improving efficiency or code functionality. I particularly liked the "verbose" flag for printing the function and parameters.

**Comment by rahil-makadia** [comment]
Thanks for the comments! I ended up running with the single file setup because by the time I had gotten everything done and realized how messy it was to just have everything in one file, I was already in too deep :). I ended up keeping the plotting functions separate since I couldn't figure out a nice way to take the common aspects of both environments into a single plotting function but I'll definitely keep both of these suggestions in mind for the next assignment.

**Pull request merged**
